# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-24 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='标题')),
                ('intro', models.CharField(max_length=255, verbose_name='简介')),
                ('content', mdeditor.fields.MDTextField(verbose_name='编写文章')),
                ('watch', models.IntegerField(verbose_name='访问次数')),
                ('img', models.ImageField(upload_to='blog/%m-%d')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '博客列表',
                'verbose_name_plural': '博客列表',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分类')),
            ],
            options={
                'verbose_name': '博客分类',
                'verbose_name_plural': '博客分类',
            },
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('head_img', models.ImageField(upload_to='head_img', verbose_name='头像')),
                ('detail', mdeditor.fields.MDTextField()),
            ],
            options={
                'verbose_name': '博主信息',
                'verbose_name_plural': '博主信息',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='标签名称')),
            ],
            options={
                'verbose_name': '个人标签',
                'verbose_name_plural': '个人标签',
            },
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='tag',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='blog',
            name='cate',
            field=models.ManyToManyField(to='blog.Cate', verbose_name='分类'),
        ),
    ]
